export const ATLAS_KEY = {
  UI_COMPONENT: "ui-component",
  CHARACTER: "character",
  DAMAGED: "damaged",
  MAAT_SPRITE: "maat-sprite",
};

export const TEXTURE_KEY = {
  // In ui-component atlas
  LIBRA_LARGE: "libra-large.png",
  LIBRA_YELLOW: "libra-yellow.png",
  LIBRA_BLUE: "libra-blue.png",
  LIBRA_RED: "libra-red.png",
  LIBRA_GREEN: "libra-green.png",
  RULER: "ruler.png",
  LOCK: "lock.png",
  NUMBER_DISPLAY_BOX: "number-display-box.png",
  BALANCED_DISPLAY_BOX: "balanced-display-box.png",
  BLOOD_BAR_BOX: "blood-bar-box.png",
  CARD_BG: "card-bg.png",
  CARD_TOP: "card-top.png",
  CARD_BG_RED: "card-bg_red.png",
  CARD_TOP_RED: "card-top_red.png",
  SHIELD_ICON: "shield-icon.png",
  SILVER_SHIELD_ICON: "silver-shield-icon.png",
  VENOM: "venom.png",
  SPOTLIGHT: "spotlight.png",
  CARD_FEATHER: "card-feather.png",
  CARD_FIST: "card-fist.png",
  CARD_SHIELD: "card-shield.png",
  FOG: "fog.png",
  PYRAMIDS: "pyramids.png",
  MAAT_SMILE: "maat-smile.png",
  APOPHIS_CRY: "apophis-cry.png",
  MAAT: "maat.png",
  CARD_FEATHER_DRAW: "card-feather-draw.png",
  CARD_SHIELD_DRAW: "card-shield-draw.png",
  CARD_IMBALANCE_DRAW: "card-imbalance-draw.png",

  // In character atlas
  SHABTI: "shabti.png",
  JACKAL: "jackal.png",
  TURTLE: "turtle.png",
  FOX: "fox.png",
  MEERKAT: "meerkat.png",
  SNAKE: "snake.png",
  APOPHIS: "apophis.png",

  SMALL_LIBRA_SET_BG: "small-libra-set-bg",
  SMALL_LIBRA_SET_BG_2: "small-libra-set-bg-2",
  RULER_INDICATOR_YELLOW: "ruler-indicator-yellow",
  RULER_INDICATOR_BLUE: "ruler-indicator-blue",
  RULER_INDICATOR_RED: "ruler-indicator-red",
  RULER_INDICATOR_GREEN: "ruler-indicator-green",

  LARGE_LIBRA_INDICATOR_BG: "large-libra-indicator-bg",
  LARGE_LIBRA_BOX_BG: "large-libra-box-bg",
  LARGE_LIBRA_BOX_BG_2: "large-libra-box-bg-2",

  CARD_DECK: "card-deck",
  LABEL_YELLOW: "label-yellow",
  LABEL_BLUE: "label-blue",
  LABEL_RED: "label-red",
  LABEL_GREEN: "label-green",
  REST_CARD_BG: "rest-card-bg",
  BUTTON_LG_UNDER: "button-lg-under",
  BUTTON_LG_BG_TOP: "button-lg-bg-top",
  BUTTON_LG_BG_NORMAL: "button-lg-bg-normal",
  BUTTON_LG_BG_HOVER: "button-lg-bg-hover",
  BUTTON_LG_BG_DISABLED: "button-lg-bg-disabled",
  DIALOG_BG_OUTER: "dialog-bg-outer",
  DIALOG_BG_INNER: "dialog-bg-inner",
};
